name: default

service: 
- name: web
  image: gcr.io/jmahood-demo/sr:latest
  resources:
  - ref: redis/web-redis
 
router:
  domain: serverless.jmahood.com
  default-route:
    ref: service/web

redis:
- name: web-redis
